name: Paerser CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.22"

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.22"

      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum
          go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v6
